# 这是您Worker的名称
name = "google-workspace-self-registration"

# 这是Worker的主入口文件
main = "worker.js"

# 兼容性日期
compatibility_date = "2025-06-10"

# --- 这是最关键的一步 ---
# 在这里声明您的KV命名空间绑定
[[kv_namespaces]]
binding = "REG_DATA"
id = "请在这里粘贴您的KV命名空间ID"
